//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisAOI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_Models
    {
        public short ModelID { get; set; }
        public string ModelName { get; set; }
        public byte ModelTypeID { get; set; }
        public string DelaySetting { get; set; }
        public string TopMask { get; set; }
        public string BotMask { get; set; }
        public Nullable<short> lenHDCP { get; set; }
        public Nullable<short> ChipCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> IDQuality { get; set; }
    }
}
